#!/bin/bash

# Initialize
printf "$$" > ~/.cache/pidofbar
sec=0

# Update functions
update_cpu() {
  cpu=$(awk '{print $1}' /proc/loadavg)
}

update_memory() {
  memory=$(free -h | awk 'NR==2 {print $3}')
}

update_time() {
  time=$(date "+%a %b %d %I:%M %p ")
}

update_weather() {
  weather=$(curl -s "wttr.in/pittsburgh?format=1" | cut -c1)
}

update_bat() {
  if [[ -e /sys/class/power_supply/BAT1/status ]]; then
    bat_status=$(< /sys/class/power_supply/BAT1/status)
    if [[ -e /sys/class/power_supply/BAT1/capacity ]]; then
      bat_capacity=$(< /sys/class/power_supply/BAT1/capacity)
      bat="$bat_status $bat_capacity%"
    else
      bat="$bat_status (capacity not available)"
    fi
  fi
}

update_vol() {
  muted=$(pactl list sinks | awk '/Mute:/ {print $2}' | head -n 1)

  if [ "$muted" == "yes" ]; then
    vol="奄 Muted"
  else
    vol="奄 $(pactl list sinks | awk '/Volume:/ {print $5}' | head -n 1 | tr -d '%')%"
  fi
}

update_backlight() {
  if [[ -e /sys/class/backlight/intel_backlight/actual_brightness ]]; then
    actual_brightness=$(< /sys/class/backlight/intel_backlight/actual_brightness)
    max_brightness=$(< /sys/class/backlight/intel_backlight/max_brightness)
    backlight="☀$((actual_brightness * 100 / max_brightness))%"
  else
    backlight="Backlight not available"
  fi
}

# Display function
display() {
  status=""
  [[ -n "$bat" ]] && status+="$bat "
  [[ -n "$backlight" ]] && status+="$backlight "
  [[ -n "$vol" ]] && status+="$vol "
  [[ -n "$time" ]] && status+="$time"
  xsetroot -name "$status"
}

# Set up signal handlers
trap "update_vol; display" "RTMIN"

# Initial updates
update_vol
update_backlight

# Main loop
while true; do
  sleep 1
  update_bat
  update_backlight
  update_time
  update_vol
  display
done